# Generated by Django 5.1.7 on 2025-03-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
    ]
