# Generated by Django 5.1.7 on 2025-03-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todolist', '0002_remove_todo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
